### ISSUE TITLE
Doesn't work with <a> in titles (<h1>, <h2>, ...)

### ISSUE THREAD

**Issue by ElisabethStereosuper** [victorloux/espaceFine#1]
Salut,
D'abord merci pour ton script qui m'a été très utile :)
Ceci dit, il ne fonctionne pas sur les liens placés dans des balises de titre.
Pour contourner le problème j'ai ajouté " || _nodeActuel.nodeType === 3 " ligne 109, mais du coup la détection des balises exclues ne fonctionne plus. 
Voila, merci d'avance!

**Comment by victorloux** [comment]
Salut Élisabeth,
merci beaucoup, c'est enfin corrigé !

J'ai fini par trouver, en fait le code qui excluait les balises était assez foireux, il excluait injustement toutes les balises `<a>` (même hors titres) alors qu'elles n'étaient pas dans la liste. 

Ce n'était pas le type de node qui était en cause, ton correctif fonctionnait juste parce que, du coup, il faisait sauter la vérification des balises exclues. Tu n'as pas mis de parenthèses, et à cause de l'ordre des opérations, l'expression finale `x || y && z` est interprétée comme `x || (y && z)`, ce qui signifie que quand l'expression `x` (est-ce que c'est un node de type 1) est vraie, ce qu'il y a à droite du `||` (`y` est-ce que c'est un node de type 3 **ET** `z` est-ce que ce n'est pas une balise exclue) n'est même pas évalué ; et donc toute la condition est vraie et les espaces corrigées. Quand la condition `x` est fausse, le reste n'est jamais vrai non plus, car un node de type 3 est un node texte, et non pas une balise, et ne peut donc pas être une balise exclue. Les joies du booléen ! 

Merci néanmoins de m'avoir donné un pointeur :)
