### ISSUE TITLE
U+202F au lieu de U+8239

### ISSUE THREAD

**Issue by moyogo** [victorloux/espaceFine#2]
La notation U+*n* utilise conventionnellement les chiffres hexadecimaux, la ligne https://github.com/victorloux/espaceFine/blame/master/readme.md#L9 devrait donc utiliser « U+202F » au lieu de « U+8239 » (202F base seize == 8239 base dix) pour U+202F NARROW NO-BREAK SPACE.

Voir http://www.unicode.org/versions/Unicode9.0.0/appA.pdf
> In running text, an individual Unicode code point is expressed as U+n, where n is four to
six hexadecimal digits, using the digits 0–9 and uppercase letters A–F (for 10 through 15,
respectively).  Leading zeros are omitted, unless the code point would have fewer than four
hexadecimal digits [...]

**Comment by victorloux** [comment]
Exact, merci !
