### ISSUE TITLE
Guillemets simples

### ISSUE THREAD

**Issue by anthonymasure** [victorloux/espaceFine#3]
Merci pour ce script très utile ! J'aimerais intégrer, en plus de ce qu'il y a déjà, des espaces dans les guillemets simples "‹" et "›" qui servent pour citer dans les guillemets doubles. Comment puis-je faire ?

**Comment by victorloux** [comment]
Il faut modifier le script original, ligne 38 :
https://github.com/victorloux/espaceFine/blob/master/src/espacefine.js#L38

& remplacer la ligne originale par ceci :
```js
var regex = new RegExp(/(\u00AB|\u2014|\u2039)(?:\s+)?|(?:\s+)?([\?!:;\u00BB\u203A])/g),
```

J’y ai ajouté `\u2039` au début qui correspond à `‹`, et `\u203A` dans la deuxième partie qui correspond à `›`. (Je n’ai pas le temps de tester mais ça devrait marcher, dis-moi si ça ne fonctionne pas !)

**Comment by anthonymasure** [comment]
Merci beaucoup, ça marche très bien !
