### ISSUE TITLE
Utilisation sur du texte pur ?

### ISSUE THREAD

**Issue by thom4parisot** [victorloux/espaceFine#4]
Salut,

je suis content de tomber sur ta librairie. Je vais bientôt avoir un besoin similaire dans oncletom/nodebook#254 mais j'ai l'impression qu'`espaceFine` ne fonctionne que sur des nœuds DOM ?

Ça t'intéresserait une contrib qui permette 1) d'appliquer ça sur du texte et 2) de rendre personnalisable le caractère inséré ?

Genre :

```js
const text = 'Comment ça va ? Bien et toi ?';

espaceFine(text, { THIN_SPACE: '{nbsp}' });
// >> "Comment ça va{nbsp}? Bien et toi{nbsp}?"
```

Je pensais brancher ça comme un plugin pour asciidoctor.js, au niveau du parsing du texte, avant que ça soit transformé en HTML/PDF/etc.

**Comment by victorloux** [comment]
Salut Thomas,

En soi, cette librairie est un très bête rechercher-remplacer sur un bloc de texte à partir d'[une expression régulière](https://github.com/victorloux/espaceFine/blob/master/src/espacefine.js#L38). Le reste du code s'occupe de faire ces rechercher-remplacers récursivement sur certains nœuds DOM (pour ne pas aller mettre des espaces insécables dans des attributs ou certaines balises type `<pre>` ou `<code>` par exemple), mais rien ne t'interdit de copier cette expression régulière et de la réutiliser sur un bloc de texte simple. Libre à toi de choisir ce qui est remplacé aussi (pour une "vraie" espace fine si elle est disponible).

Je n'ai pas d'expérience avec AsciiDoctor mais si mon code n'est pas clair je peux prêter une main !

**Comment by thom4parisot** [comment]
Nickel merci.

Je vais commencer au plus simple déjà et je te tiens au jus :-)

**Comment by thom4parisot** [comment]
Tiens, j'ai intégré la regexp à Asciidoctor.js dans le projet [`oncletom/nodebook`](https://github.com/oncletom/nodebook/blob/master/src/asciidoctor-microtypography-french.js).

Je serais partant pour écrire (ou pairer sur l'écriture) des tests unitaires et modulariser ce bout — fin juillet/août.
